/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package haydtpc04386_lab8;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author dutru
 */
public class Location extends javax.swing.JFrame {

    /**
     * Creates new form Location
     */
    public Location() {
        initComponents();
        LoadDataToComboBoxTinhThanhPho();
    }
    static String name ="UserAdmin";
    static String pass = "123456";
    static String url = "jdbc:sqlserver://localhost:1433;databaseName=TinhThanhVietNam;encrypt=true;trustServerCertificate=true";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboTinhThanhPho = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboQuanHuyen = new javax.swing.JComboBox<>();
        cboPhuongXa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("LOCATION");

        cboTinhThanhPho.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTinhThanhPhoItemStateChanged(evt);
            }
        });
        cboTinhThanhPho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboTinhThanhPhoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboTinhThanhPhoMousePressed(evt);
            }
        });
        cboTinhThanhPho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTinhThanhPhoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tỉnh/Thành phố:");

        jLabel3.setText("Quận/Huyện:");

        cboQuanHuyen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboQuanHuyenItemStateChanged(evt);
            }
        });
        cboQuanHuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboQuanHuyenMouseClicked(evt);
            }
        });

        cboPhuongXa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboPhuongXaMouseClicked(evt);
            }
        });

        jLabel4.setText("Phường/Xã:");

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXacNhan)
                    .addComponent(cboPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cboTinhThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTinhThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnXacNhan)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboTinhThanhPhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTinhThanhPhoMouseClicked
//        LoadDataToComboBoxQuanHuyen();
    }//GEN-LAST:event_cboTinhThanhPhoMouseClicked

    private void cboQuanHuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboQuanHuyenMouseClicked
//        LoadDataToComboBoxPhuongXa();
    }//GEN-LAST:event_cboQuanHuyenMouseClicked

    private void cboTinhThanhPhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTinhThanhPhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTinhThanhPhoActionPerformed

    private void cboPhuongXaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboPhuongXaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPhuongXaMouseClicked

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        JOptionPane.showMessageDialog(this, "Địa chỉ: "+cboPhuongXa.getSelectedItem().toString()+", "+cboQuanHuyen.getSelectedItem().toString()+", "+cboTinhThanhPho.getSelectedItem().toString());
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void cboTinhThanhPhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTinhThanhPhoMousePressed
//        LoadDataToComboBoxQuanHuyen();
    }//GEN-LAST:event_cboTinhThanhPhoMousePressed

    private void cboTinhThanhPhoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTinhThanhPhoItemStateChanged
        LoadDataToComboBoxQuanHuyen();
    }//GEN-LAST:event_cboTinhThanhPhoItemStateChanged

    private void cboQuanHuyenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboQuanHuyenItemStateChanged
        LoadDataToComboBoxPhuongXa();
    }//GEN-LAST:event_cboQuanHuyenItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Location().setVisible(true);
            }
        });
    }
    public void LoadDataToComboBoxTinhThanhPho(){
        try{
            cboTinhThanhPho.removeAllItems();
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, name, pass);
            Statement st = con.createStatement();
            String sql = "  SELECT full_name FROM provinces";
            ResultSet rs = st.executeQuery(sql);
            String check = null;
            while(rs.next()){
                String s = rs.getString(1);
                cboTinhThanhPho.setSelectedItem(rs.getString(1));
                if (s.equals(check) == false){
                    cboTinhThanhPho.addItem(s);
                    check = s;
                }
                
            }
            con.close();
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    public void LoadDataToComboBoxQuanHuyen(){
        try{
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, name, pass);
            String sql = "select code from provinces where full_name=?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, cboTinhThanhPho.getSelectedItem().toString());
            ResultSet rs = st.executeQuery();
            rs.next();
            String maTinh = rs.getString(1);
            String sql2 = "  SELECT full_name FROM districts WHERE province_code = ?";
            PreparedStatement st2 = con.prepareStatement(sql2);
            st2.setString(1, maTinh);
            ResultSet rs2 = st2.executeQuery();
            
            String check = null;
            cboQuanHuyen.removeAllItems();
            while(rs2.next()){
                String s = rs2.getString(1);
                cboQuanHuyen.setSelectedItem(rs2.getString(1));
                if (s.equals(check) == false){
                    cboQuanHuyen.addItem(s);
                    check = s;
                }
                
            }
            con.close();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    public void LoadDataToComboBoxPhuongXa(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url, name, pass);
            String sql = "select code from districts where full_name=?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, cboQuanHuyen.getSelectedItem().toString());
            ResultSet rs = st.executeQuery();
            rs.next();
            String maHuyen = rs.getString(1);
            String sql2 = "  SELECT full_name FROM wards WHERE district_code = ?";
            PreparedStatement st2 = con.prepareStatement(sql2);
            st2.setString(1, maHuyen);
            ResultSet rs2 = st2.executeQuery();
            
            String check = null;
            cboPhuongXa.removeAllItems();
            while(rs2.next()){
                String s = rs2.getString(1);
                cboPhuongXa.setSelectedItem(rs2.getString(1));
                if (s.equals(check) == false){
                    cboPhuongXa.addItem(s);
                    check = s;
                }
                
            }
            con.close();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnXacNhan;
    private javax.swing.JComboBox<String> cboPhuongXa;
    private javax.swing.JComboBox<String> cboQuanHuyen;
    private javax.swing.JComboBox<String> cboTinhThanhPho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
